[read]
database = './data.db'
read = './test/test.txt'

[output]
misc = './test/misc.txt'
removed = './test/removed.txt'
check = './test/check.txt'

[display]
optimize_layout = false
group_by_month = false # Is ignored if optimize is enabled

[keybinds]
clipper = 'F5'